title: West Harbor Equity Partners
description: Strategic Capital. Operational Excellence.
baseurl: ""
url: "https://westharborequity.com"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-sitemap

# GitHub Pages specific settings
github: [metadata]

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
